// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQ-GVQmdY6Y2AYQGAryZ32J2c5B6Px3U',
    appId: '1:277516011054:web:f7da3effba1fe0fc84c1bf',
    messagingSenderId: '277516011054',
    projectId: 'finance-app-3f383',
    authDomain: 'finance-app-3f383.firebaseapp.com',
    storageBucket: 'finance-app-3f383.appspot.com',
    measurementId: 'G-7M4592421S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnrEYGqEQ3sKzZ7cZMtW-a-wcUR_u7STw',
    appId: '1:277516011054:android:bc93fa21389d129484c1bf',
    messagingSenderId: '277516011054',
    projectId: 'finance-app-3f383',
    storageBucket: 'finance-app-3f383.appspot.com',
  );
}
